//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace malltopic_wcf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aprovaciones
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> fk_promo { get; set; }
        public Nullable<System.Guid> fk_evento { get; set; }
        public int tipo { get; set; }
        public Nullable<System.DateTime> creado { get; set; }
        public Nullable<System.DateTime> modificado { get; set; }
        public Nullable<System.Guid> user_creado { get; set; }
        public Nullable<System.Guid> user_modificado { get; set; }
        public bool Aprovado { get; set; }
        public System.Guid fk_cc { get; set; }
    
        public Promos Promos { get; set; }
        public Events Events { get; set; }
        public Malls Malls { get; set; }
    }
}
