//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace malltopic_wcf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colections
    {
        public Colections()
        {
            this.Colections_detail = new HashSet<Colections_detail>();
        }
    
        public System.Guid id { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> fechaLanzamiento { get; set; }
        public Nullable<bool> publicar { get; set; }
        public Nullable<System.DateTime> creado { get; set; }
        public Nullable<System.DateTime> modificado { get; set; }
        public Nullable<System.Guid> user_created { get; set; }
        public Nullable<System.Guid> user_modified { get; set; }
        public Nullable<System.Guid> fk_IdStore { get; set; }
        public Nullable<int> año { get; set; }
        public Nullable<bool> especial { get; set; }
        public Nullable<System.Guid> fk_idCC { get; set; }
        public string descripcion { get; set; }
    
        public virtual Stores Stores { get; set; }
        public virtual Malls Malls { get; set; }
        public virtual ICollection<Colections_detail> Colections_detail { get; set; }
    }
}
