//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace malltopic_wcf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorites
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> IdMall { get; set; }
        public Nullable<System.Guid> IdLocal { get; set; }
    
        public Malls Malls { get; set; }
        public Stores Stores { get; set; }
    }
}
