//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace malltopic_wcf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery
    {
        public Gallery()
        {
            this.Gallery_detail = new HashSet<Gallery_detail>();
        }
    
        public System.Guid id { get; set; }
        public string portada { get; set; }
        public Nullable<System.Guid> fk_idMall { get; set; }
        public Nullable<System.Guid> fk_idStore { get; set; }
        public Nullable<System.Guid> user_create { get; set; }
        public Nullable<System.Guid> user_modified { get; set; }
        public Nullable<System.DateTime> creado { get; set; }
        public Nullable<System.DateTime> modificado { get; set; }
    
        public virtual ICollection<Gallery_detail> Gallery_detail { get; set; }
        public virtual Malls Malls { get; set; }
        public virtual Stores Stores { get; set; }
    }
}
