//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace malltopic_wcf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Malls
    {
        public Malls()
        {
            this.Aprovaciones = new HashSet<Aprovaciones>();
            this.Categories = new HashSet<Categories>();
            this.Cinema = new HashSet<Cinema>();
            this.Colections = new HashSet<Colections>();
            this.Events = new HashSet<Events>();
            this.Favorites = new HashSet<Favorites>();
            this.Gallery = new HashSet<Gallery>();
            this.Stores = new HashSet<Stores>();
            this.PilasPs = new HashSet<PilasPs>();
            this.Promos = new HashSet<Promos>();
            this.Room_movie = new HashSet<Room_movie>();
            this.services_detail = new HashSet<services_detail>();
            this.transport = new HashSet<transport>();
            this.Movies = new HashSet<Movies>();
        }
    
        public System.Guid id { get; set; }
        public string nombre { get; set; }
        public string mapa { get; set; }
        public string web { get; set; }
        public string direccion { get; set; }
        public Nullable<decimal> telefono { get; set; }
        public string horarios { get; set; }
        public string descripcion { get; set; }
        public string slogan { get; set; }
        public string imagen { get; set; }
        public string colorFondo { get; set; }
        public string colorLetra { get; set; }
        public Nullable<int> cantParqueadero { get; set; }
        public Nullable<int> cantLocales { get; set; }
        public string galeriaImagenes { get; set; }
        public string correo { get; set; }
        public Nullable<System.DateTime> creado { get; set; }
        public Nullable<System.DateTime> modificado { get; set; }
        public Nullable<System.Guid> user_created { get; set; }
        public Nullable<System.Guid> user_modified { get; set; }
        public Nullable<bool> publicar { get; set; }
        public Nullable<System.Guid> fk_ciudad { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
        public string facebook { get; set; }
        public string twitter { get; set; }
        public Nullable<int> orden { get; set; }
        public string H_lunes_a_viernes { get; set; }
        public string H_sabado { get; set; }
        public string H_domingos_y_festivos { get; set; }
        public string youtube { get; set; }
        public string Instagram { get; set; }
    
        public virtual ICollection<Aprovaciones> Aprovaciones { get; set; }
        public virtual ICollection<Categories> Categories { get; set; }
        public virtual ICollection<Cinema> Cinema { get; set; }
        public virtual Cities Cities { get; set; }
        public virtual ICollection<Colections> Colections { get; set; }
        public virtual ICollection<Events> Events { get; set; }
        public virtual ICollection<Favorites> Favorites { get; set; }
        public virtual ICollection<Gallery> Gallery { get; set; }
        public virtual ICollection<Stores> Stores { get; set; }
        public virtual ICollection<PilasPs> PilasPs { get; set; }
        public virtual ICollection<Promos> Promos { get; set; }
        public virtual ICollection<Room_movie> Room_movie { get; set; }
        public virtual ICollection<services_detail> services_detail { get; set; }
        public virtual ICollection<transport> transport { get; set; }
        public virtual ICollection<Movies> Movies { get; set; }
    }
}
