//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace malltopic_wcf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public Movies()
        {
            this.Schedule_movie = new HashSet<Schedule_movie>();
            this.Room_movie = new HashSet<Room_movie>();
            this.Malls = new HashSet<Malls>();
        }
    
        public System.Guid id { get; set; }
        public string actores { get; set; }
        public string censura { get; set; }
        public string duracion { get; set; }
        public Nullable<bool> estreno { get; set; }
        public string genero { get; set; }
        public string portada { get; set; }
        public string formato { get; set; }
        public string titulo { get; set; }
        public Nullable<bool> publicar { get; set; }
        public Nullable<System.Guid> user_created { get; set; }
        public Nullable<System.Guid> user_modified { get; set; }
        public Nullable<System.DateTime> creado { get; set; }
        public Nullable<System.DateTime> modificado { get; set; }
        public string sinopsis { get; set; }
        public string trailer { get; set; }
        public string director { get; set; }
    
        public ICollection<Schedule_movie> Schedule_movie { get; set; }
        public ICollection<Room_movie> Room_movie { get; set; }
        public ICollection<Malls> Malls { get; set; }
    }
}
