//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace malltopic_wcf
{
    using System;
    using System.Collections.Generic;
    
    public partial class PilasPs
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> fk_idCC { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public string link { get; set; }
    
        public virtual Malls Malls { get; set; }
    }
}
