//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace malltopic_wcf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room_movie
    {
        public Room_movie()
        {
            this.Schedule_movie = new HashSet<Schedule_movie>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<int> capacidad { get; set; }
        public string descripcion { get; set; }
        public string nombre { get; set; }
        public Nullable<bool> publicar { get; set; }
        public Nullable<System.Guid> fk_cine { get; set; }
        public Nullable<System.Guid> user_created { get; set; }
        public Nullable<System.Guid> user_modified { get; set; }
        public Nullable<System.DateTime> creado { get; set; }
        public Nullable<System.DateTime> modificado { get; set; }
        public Nullable<System.Guid> fk_idCC { get; set; }
    
        public Malls Malls { get; set; }
        public Movies Movies { get; set; }
        public ICollection<Schedule_movie> Schedule_movie { get; set; }
    }
}
