//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace malltopic_wcf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule_movie
    {
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> fechaProyeccion { get; set; }
        public string hora { get; set; }
        public Nullable<double> precio { get; set; }
        public Nullable<System.Guid> user_created { get; set; }
        public Nullable<System.Guid> user_modified { get; set; }
        public Nullable<System.DateTime> creado { get; set; }
        public Nullable<System.DateTime> modificado { get; set; }
        public Nullable<System.Guid> fk_cine { get; set; }
        public Nullable<System.Guid> fk_pelicula { get; set; }
        public Nullable<System.Guid> fk_sala { get; set; }
    
        public virtual Cinema Cinema { get; set; }
        public virtual Movies Movies { get; set; }
        public virtual Room_movie Room_movie { get; set; }
    }
}
