//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace malltopic_wcf
{
    using System;
    using System.Collections.Generic;
    
    public partial class services_detail
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> fk_IdCC { get; set; }
        public Nullable<System.Guid> fk_IdServicio { get; set; }
        public Nullable<int> orden { get; set; }
    
        public Malls Malls { get; set; }
        public Services Services { get; set; }
    }
}
