//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace malltopic_wcf
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoresXCategories
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> fk_idCategory { get; set; }
        public Nullable<System.Guid> fk_idstore { get; set; }
    
        public Categories Categories { get; set; }
        public Stores Stores { get; set; }
    }
}
