//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MallTopic_News.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorias
    {
        public string id { get; set; }
        public string nombre { get; set; }
        public string estilo { get; set; }
        public Nullable<System.DateTimeOffset> creado { get; set; }
        public Nullable<System.DateTimeOffset> modificado { get; set; }
        public string usuario_creado { get; set; }
        public string usuario_modificado { get; set; }
    }
}
