//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MallTopic_News.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Malls
    {
        public System.Guid id { get; set; }
        public string nombre { get; set; }
        public string mapa { get; set; }
        public string web { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string horarios { get; set; }
        public string descripcion { get; set; }
        public string slogan { get; set; }
        public string imagen { get; set; }
        public string colorFondo { get; set; }
        public string colorLetra { get; set; }
        public Nullable<int> cantParqueadero { get; set; }
        public Nullable<int> cantLocales { get; set; }
        public string galeriaImagenes { get; set; }
        public string correo { get; set; }
        public Nullable<System.DateTime> creado { get; set; }
        public Nullable<System.DateTime> modificado { get; set; }
        public Nullable<System.Guid> user_created { get; set; }
        public Nullable<System.Guid> user_modified { get; set; }
        public Nullable<bool> publicar { get; set; }
        public Nullable<System.Guid> fk_ciudad { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
        public string Twitter { get; set; }
        public string Facebook { get; set; }
        public string H_lunes_a_viernes { get; set; }
        public string H_sabado { get; set; }
        public string H_domingos_y_festivos { get; set; }
        public Nullable<int> orden { get; set; }

    }
}
