//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalltopicNewsCMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Noticias
    {
        public string id { get; set; }

        [Required(ErrorMessage = "Debe ingresar un título")]
        [Display(Name = "Título")]
        public string titulo { get; set; }

        [Required(ErrorMessage = "Debe ingresar una descripción")]
        [Display(Name = "Descripción")]
        public string descripcion { get; set; }

        [Display(Name = "Pie de imagen")]
        public string pie_de_imagen { get; set; }

        [Display(Name = "Link")]
        public string link { get; set; }

        [Required(ErrorMessage = "Debe ingresar una categoría")]
        [Display(Name = "Categoría")]
        public string fk_idcategoria { get; set; }

        public string idportada { get; set; }
        public string usuario_creado { get; set; }
        public string usuario_modificado { get; set; }

        [Display(Name = "Publicar")]
        public Nullable<bool> publicar { get; set; }

        [Display(Name = "Destacado")]
        public Nullable<bool> destacado { get; set; }

        [Required(ErrorMessage = "Debe ingresar un fecha de publicación")]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Date, ErrorMessage = "El formato es incorrecto")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Fecha de publicación")]
        public Nullable<System.DateTimeOffset> fecha_publicado { get; set; }
        public Nullable<System.DateTimeOffset> creado { get; set; }
        public Nullable<System.DateTimeOffset> modificado { get; set; }
        public string imagenes { get; set; }

        [Required(ErrorMessage = "Debe ingresar una autor")]
        [Display(Name = "Autor")]
        public string autor { get; set; }
    }
}
